// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace StoreApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Entities.Models.CartLine", b =>
                {
                    b.Property<int>("CartLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartLineId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductID");

                    b.ToTable("CartLine");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "InternalParts"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "ExternalParts"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Connectivity"
                        });
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GiftWrap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Line2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Line3")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OrderedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Shipped")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryId = 1,
                            ImageUrl = "/images/1.jpg",
                            Price = 200m,
                            ProductName = "Ryzen 5 3600",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryId = 1,
                            ImageUrl = "/images/2.jpg",
                            Price = 80m,
                            ProductName = "Corsair Vengeance 16GB",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryId = 1,
                            ImageUrl = "/images/3.jpg",
                            Price = 120m,
                            ProductName = "Samsung 970 EVO Plus 1TB",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryId = 1,
                            ImageUrl = "/images/4.jpg",
                            Price = 40m,
                            ProductName = "Western Digital 1TB",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryId = 1,
                            ImageUrl = "/images/5.jpg",
                            Price = 250m,
                            ProductName = "MSI GeForce GTX 1660",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryId = 1,
                            ImageUrl = "/images/6.jpg",
                            Price = 35m,
                            ProductName = "Cooler Master Hyper 212",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryId = 1,
                            ImageUrl = "/images/7.jpg",
                            Price = 90m,
                            ProductName = "ASUS ROG Strix B450-F",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryId = 1,
                            ImageUrl = "/images/8.jpg",
                            Price = 90m,
                            ProductName = "Noctua NH-D15",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryId = 1,
                            ImageUrl = "/images/9.jpg",
                            Price = 120m,
                            ProductName = "Corsair RM850x",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryId = 1,
                            ImageUrl = "/images/10.jpg",
                            Price = 60m,
                            ProductName = "Cooler Master MasterBox Q300L",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 11,
                            CategoryId = 1,
                            ImageUrl = "/images/11.jpg",
                            Price = 55m,
                            ProductName = "Kingston A2000 500GB",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 12,
                            CategoryId = 1,
                            ImageUrl = "/images/12.jpg",
                            Price = 150m,
                            ProductName = "Corsair iCUE H150i Elite Capellix",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 13,
                            CategoryId = 1,
                            ImageUrl = "/images/13.jpg",
                            Price = 180m,
                            ProductName = "G.SKILL Ripjaws V 32GB",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 14,
                            CategoryId = 1,
                            ImageUrl = "/images/14.jpg",
                            Price = 350m,
                            ProductName = "Intel Core i7-10700K",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 15,
                            CategoryId = 1,
                            ImageUrl = "/images/15.jpg",
                            Price = 180m,
                            ProductName = "ASUS TUF Gaming Z490-Plus",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 16,
                            CategoryId = 1,
                            ImageUrl = "/images/16.jpg",
                            Price = 90m,
                            ProductName = "Be Quiet! Dark Rock Pro 4",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 17,
                            CategoryId = 1,
                            ImageUrl = "/images/17.jpg",
                            Price = 90m,
                            ProductName = "Samsung 970 EVO 500GB",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 18,
                            CategoryId = 1,
                            ImageUrl = "/images/18.jpg",
                            Price = 500m,
                            ProductName = "EVGA GeForce RTX 3070",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 19,
                            CategoryId = 2,
                            ImageUrl = "/images/19.jpg",
                            Price = 60m,
                            ProductName = "Logitech G502",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 20,
                            CategoryId = 2,
                            ImageUrl = "/images/20.jpg",
                            Price = 150m,
                            ProductName = "Corsair K95 RGB",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 21,
                            CategoryId = 2,
                            ImageUrl = "/images/21.jpg",
                            Price = 400m,
                            ProductName = "Samsung Odyssey G7 32",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 22,
                            CategoryId = 2,
                            ImageUrl = "/images/22.jpg",
                            Price = 100m,
                            ProductName = "Razer Kraken V3",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 23,
                            CategoryId = 2,
                            ImageUrl = "/images/23.jpg",
                            Price = 100m,
                            ProductName = "JBL Flip 5",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 24,
                            CategoryId = 2,
                            ImageUrl = "/images/24.jpg",
                            Price = 130m,
                            ProductName = "Logitech G Pro X",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 25,
                            CategoryId = 2,
                            ImageUrl = "/images/25.jpg",
                            Price = 250m,
                            ProductName = "SteelSeries Apex Pro",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 26,
                            CategoryId = 2,
                            ImageUrl = "/images/26.jpg",
                            Price = 500m,
                            ProductName = "Alienware AW2521H 24.5",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 27,
                            CategoryId = 2,
                            ImageUrl = "/images/27.jpg",
                            Price = 130m,
                            ProductName = "Logitech G903 LIGHTSPEED",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 28,
                            CategoryId = 2,
                            ImageUrl = "/images/28.jpg",
                            Price = 150m,
                            ProductName = "Razer Nari Ultimate",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 29,
                            CategoryId = 2,
                            ImageUrl = "/images/29.jpg",
                            Price = 90m,
                            ProductName = "HyperX Cloud II",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 30,
                            CategoryId = 2,
                            ImageUrl = "/images/30.jpg",
                            Price = 300m,
                            ProductName = "BenQ ZOWIE XL2546K",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 31,
                            CategoryId = 2,
                            ImageUrl = "/images/31.jpg",
                            Price = 200m,
                            ProductName = "Logitech Z906",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 32,
                            CategoryId = 2,
                            ImageUrl = "/images/32.jpg",
                            Price = 90m,
                            ProductName = "SteelSeries Rival 600",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 33,
                            CategoryId = 2,
                            ImageUrl = "/images/33.jpg",
                            Price = 70m,
                            ProductName = "Razer DeathAdder Elite",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 34,
                            CategoryId = 3,
                            ImageUrl = "/images/34.jpg",
                            Price = 90m,
                            ProductName = "TP-Link Archer AX50",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 35,
                            CategoryId = 3,
                            ImageUrl = "/images/35.jpg",
                            Price = 130m,
                            ProductName = "Netgear Nighthawk R7000",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 36,
                            CategoryId = 3,
                            ImageUrl = "/images/36.jpg",
                            Price = 35m,
                            ProductName = "TP-Link RE200",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 37,
                            CategoryId = 3,
                            ImageUrl = "/images/37.jpg",
                            Price = 40m,
                            ProductName = "Google Chromecast",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 38,
                            CategoryId = 3,
                            ImageUrl = "/images/38.jpg",
                            Price = 90m,
                            ProductName = "ASUS RT-AC68U",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 39,
                            CategoryId = 3,
                            ImageUrl = "/images/39.jpg",
                            Price = 120m,
                            ProductName = "TP-Link Deco M5",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 40,
                            CategoryId = 3,
                            ImageUrl = "/images/40.jpg",
                            Price = 70m,
                            ProductName = "D-Link DIR-878",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 41,
                            CategoryId = 3,
                            ImageUrl = "/images/41.jpg",
                            Price = 110m,
                            ProductName = "Linksys EA7500",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 42,
                            CategoryId = 3,
                            ImageUrl = "/images/42.jpg",
                            Price = 250m,
                            ProductName = "Netgear Orbi RBK50",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 43,
                            CategoryId = 3,
                            ImageUrl = "/images/43.jpg",
                            Price = 80m,
                            ProductName = "Tenda Nova MW6",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 44,
                            CategoryId = 3,
                            ImageUrl = "/images/44.jpg",
                            Price = 30m,
                            ProductName = "Xiaomi Mi WiFi Router 4",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 45,
                            CategoryId = 3,
                            ImageUrl = "/images/45.jpg",
                            Price = 40m,
                            ProductName = "TP-Link Tether",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 46,
                            CategoryId = 3,
                            ImageUrl = "/images/46.jpg",
                            Price = 160m,
                            ProductName = "Linksys WRT3200ACM",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 47,
                            CategoryId = 3,
                            ImageUrl = "/images/47.jpg",
                            Price = 300m,
                            ProductName = "Ubiquiti UniFi Dream Machine",
                            Summary = ""
                        });
                });

            modelBuilder.Entity("Entities.Models.CartLine", b =>
                {
                    b.HasOne("Entities.Models.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId");

                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
